In [1]:
import pandas as pd
import yfinance as yf
from helpers import drop_nan_days, filter_daily_volume
import pyarrow.parquet as pq

In [15]:
tmp = pd.read_csv("AllUSData-27-02-2026.csv", header=[0, 1], index_col=0)

In [42]:
tmp = pd.read_parquet("AllUSData-2y-03-03-2026-pyarrow.parquet")

In [43]:
tmp

Price        Close                                                  \
Ticker        AACB AACBR  AACBU  AACG AACIU AACOU    AAL      AAME
Date
2024-03-04     NaN   NaN    NaN  1.49   NaN   NaN  14.81  2.576890
2024-03-05     NaN   NaN    NaN  1.46   NaN   NaN  14.67  2.645217
2024-03-06     NaN   NaN    NaN  1.61   NaN   NaN  14.88  2.654978
2024-03-07     NaN   NaN    NaN  1.51   NaN   NaN  14.90  2.733065
2024-03-08     NaN   NaN    NaN  1.57   NaN   NaN  14.68  2.762348
...            ...   ...    ...   ...   ...   ...    ...       ...
2026-02-24  10.341   NaN  10.60  0.93  9.98  9.94  13.15  2.700000
2026-02-25  10.341   NaN  10.60  1.00  9.97  9.95  13.32  2.690000
2026-02-26  10.341   NaN  10.60  0.98  9.97  9.95  13.94  2.690000
2026-02-27  10.341   NaN  10.60  1.02  9.97  9.94  13.07  2.620000
2026-03-02  10.341   0.3  10.53  0.99  9.97  9.95  12.52  2.590000

Price                               ... High  Low Open Volume Adj Close Close  \
Ticker            AAOI        AAON  ... VLN+ VLN+ VLN+   VLN+     WFC-Z WFC-Z
Date                                ...
2024-03-04   14.960000   81.830383  ...  NaN  NaN  NaN    NaN       NaN   NaN
2024-03-05   14.740000   80.263199  ...  NaN  NaN  NaN    NaN       NaN   NaN
2024-03-06   14.900000   80.342560  ...  NaN  NaN  NaN    NaN       NaN   NaN
2024-03-07   14.840000   80.461578  ...  NaN  NaN  NaN    NaN       NaN   NaN
2024-03-08   14.760000   81.086464  ...  NaN  NaN  NaN    NaN       NaN   NaN
...                ...         ...  ...  ...  ...  ...    ...       ...   ...
2026-02-24   56.270000  100.949997  ...  NaN  NaN  NaN    NaN       NaN   NaN
2026-02-25   58.119999   99.050003  ...  NaN  NaN  NaN    NaN       NaN   NaN
2026-02-26   53.689999   98.889999  ...  NaN  NaN  NaN    NaN       NaN   NaN
2026-02-27   84.230003  101.199997  ...  NaN  NaN  NaN    NaN       NaN   NaN
2026-03-02  102.510002  104.730003  ...  NaN  NaN  NaN    NaN       NaN   NaN

Price       High   Low  Open Volume
Ticker     WFC-Z WFC-Z WFC-Z  WFC-Z
Date
2024-03-04   NaN   NaN   NaN    NaN
2024-03-05   NaN   NaN   NaN    NaN
2024-03-06   NaN   NaN   NaN    NaN
2024-03-07   NaN   NaN   NaN    NaN
2024-03-08   NaN   NaN   NaN    NaN
...          ...   ...   ...    ...
2026-02-24   NaN   NaN   NaN    NaN
2026-02-25   NaN   NaN   NaN    NaN
2026-02-26   NaN   NaN   NaN    NaN
2026-02-27   NaN   NaN   NaN    NaN
2026-03-02   NaN   NaN   NaN    NaN

[500 rows x 37252 columns]

In [73]:
df = tmp.copy()

In [74]:
df.index = pd.to_datetime(df.index)

In [ ]:
start_date = '2025-01-01'
end_date = '2025-12-31'
cutted_df = df[(df.index >= start_date) & (df.index <= end_date)]

:

In [78]:
cutted_df = filter_daily_volume(cutted_df, 2000000, True)
cutted_df = drop_nan_days(cutted_df, "Close", 2)

In [73]:
df = yf.download(["AAPL", "SNDK", "WDC", "LITE", "AXTI"], period="1y", interval="1d")

C:\Users\sasso\AppData\Local\Temp\ipykernel_86472\3897251713.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(["AAPL", "SNDK", "WDC", "LITE", "AXTI"], period="1y", interval="1d")
[*********************100%***********************]  5 of 5 completed

In [ ]:
closes = cutted_df["Close"]

In [80]:
change_df = closes.resample('ME').apply(lambda x: ((x.iloc[-1] - x.iloc[0]) / x.iloc[0]) * 100).to_period('M')

In [81]:
ema_returns = change_df.ewm(span=6).mean()
final_scores = ema_returns.iloc[-1]
final_scores.sort_values(ascending=False).head(20)

Ticker
CAPR    90.794111
RGC     61.923299
PRAX    61.873943
ABVX    60.084137
SBET    50.522775
OLMA    50.441532
SLS     44.365085
PACS    43.014908
OMER    41.725347
TERN    40.253177
GPCR    39.930057
WVE     39.135151
COGT    38.554505
TRON    32.185425
ONDS    31.777723
CELC    31.683664
KOD     31.447121
PL      31.371123
TE      31.180712
FEIM    29.139847
Name: 2025-12, dtype: float64

In [82]:
change_df_t = change_df.transpose()
change_df_t["FinalScore"] = final_scores
change_df_t.sort_values("FinalScore", ascending=False).head(15)

Date,2025-01,2025-02,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12,FinalScore
Ticker,,,,,,,,,,,,,
CAPR,0.534759,1.317522,-30.577910,33.966249,-22.370483,-2.742407,-15.670098,-20.506327,13.902056,-16.751917,-11.861619,333.984965,90.794111
RGC,-21.161764,20.735469,686.967771,106.967797,1038.960947,-13.431990,-9.589045,8.326907,20.233458,5.180036,-14.970506,75.732220,61.923299
PRAX,-3.734902,-51.906308,12.876303,4.934487,1.287435,5.600200,25.596487,-15.806987,17.935028,274.877391,7.950987,59.698740,61.873943
ABVX,-18.106998,29.292925,-14.733969,20.882853,-12.879883,20.472444,836.945145,12.627700,3.549218,24.296112,26.282250,12.454134,60.084137
SBET,-35.820897,-13.953485,-32.558137,-18.181819,2104.022889,-82.066100,101.176457,3.967330,0.176682,-20.322398,-18.869368,-6.875008,50.522775
OLMA,9.694793,-26.677855,-10.688837,54.491017,-0.189031,-2.628566,17.620137,2.439027,51.313760,-18.749997,236.342036,-10.554564,50.441532
SLS,51.401862,-20.270275,-6.896545,42.201826,5.555558,38.607595,-23.557688,15.662650,-12.021859,7.692307,-9.497205,151.333332,44.365085
PACS,12.374319,-9.071879,-13.935686,-11.244242,2.057611,31.702340,-14.594590,9.604524,18.464188,-13.898787,183.375742,14.528636,43.014908
OMER,-12.398377,-0.237253,0.611997,-7.079645,-55.982907,-2.597400,30.303025,15.235456,-4.428906,77.053144,35.146436,77.479336,41.725347
TERN,-21.340388,-15.560637,-18.584074,28.906251,-12.640451,13.719514,51.428573,27.239494,-0.661372,5.761847,100.356387,46.749003,40.253177
GPCR,6.314291,-16.225751,-22.515670,70.994301,-20.380533,-4.818729,-13.213071,9.721427,39.442232,27.956984,9.310144,101.186010,39.930057
WVE,-13.138138,-10.876897,-19.601992,-0.258398,-24.307302,4.000000,24.233135,11.239864,-23.908521,28.591745,-6.618534,129.419708,39.135151
COGT,19.358977,-16.240262,-14.428575,-10.017270,-3.374779,27.985734,58.171751,5.964915,19.666664,15.357389,159.483879,-10.663979,38.554505
TRON,-46.666669,21.492536,19.130439,-3.140099,40.243901,1259.649140,20.970032,-43.328932,-55.116282,34.010156,-23.236516,-34.042553,32.185425
ONDS,-33.460079,-38.499999,25.586861,-29.363637,54.626118,30.612239,8.163257,166.363637,41.391937,-11.901503,28.455284,28.759899,31.777723

In [ ]:
full_df_change_t = full_df_change.transpose()
full_df_change_t["FinalScore"] = final_scores
full_df_change_t.sort_values("FinalScore", ascending=False).head(15)

Date,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12,...,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02,2026-03,FinalScore
Ticker,,,,,,,,,,,,,,,,,,,,,
PPCB,10.344826,-56.521738,137.500010,-27.777776,-38.461540,-42.857142,-40.000000,0.000000,0.000000,-33.333338,...,140.722881,-68.541668,-37.728936,-27.058825,-20.920355,-43.066313,-60.153926,-15.683703,0.0,3194.358878
VSME,-10.952382,13.573405,-20.823244,-10.714286,-29.901962,-29.629632,-2.934784,32.530126,-1.666675,9.243688,...,33.971295,66.417908,0.799999,-71.270493,-73.584906,-30.821914,1763.157898,-30.978263,0.0,240.946451
SMX,-33.846154,11.278195,13.907284,-20.754717,-50.243902,-40.085289,7.407412,-86.535715,-38.904902,207.291672,...,-66.823530,-77.142856,-13.095243,-87.234721,3348.587642,-58.066173,-33.510891,-42.745681,0.0,220.159223
ANL,9.617275,46.808519,-48.619956,-46.905536,7.361964,-15.959659,-26.752768,0.000000,9.852219,15.732759,...,-4.666670,16.551724,1.067419,-20.555556,14.388493,-3.401365,670.289866,-15.210359,0.0,94.279335
BNAI,-37.845303,-61.394556,157.819908,-26.439235,-35.802475,-35.359118,-10.344834,-14.300003,-1.204824,29.866664,...,-16.873456,-9.144548,-2.649004,35.562313,-15.268818,-35.376045,556.498677,53.001719,0.0,87.890176
BVC,-4.477616,-40.000001,-56.505574,-45.022286,-23.684210,77.474389,-36.206894,334.999996,-26.766921,29.746836,...,-21.222221,1.141229,100.719424,-15.671644,16.018516,-3.389827,527.142849,-21.540177,0.0,76.653844
ELPW,0.281423,0.277775,0.276750,1.011956,0.180991,0.225527,1.079136,-33.985763,-81.955924,-6.382973,...,339.675175,-91.126761,-1.618122,-1.219515,-27.000004,-46.344337,626.041661,-91.940298,0.0,70.406434
XWEL,-18.357483,6.586827,-8.771935,12.499995,16.477271,-2.564106,-6.989247,3.468205,-20.348838,7.857144,...,10.869561,9.900993,-10.000001,-11.111112,-14.606741,-41.025638,-28.888889,380.645161,0.0,67.474720
CDIO,10.077513,-50.719427,-0.716331,-21.316163,-16.666671,-18.300656,-32.424239,35.265694,16.923073,206.688957,...,14.681440,-1.804128,3.084836,-5.164325,-27.638188,-6.228376,-46.830985,351.724136,0.0,61.759757
SPRB,-85.363128,-13.658537,3.347280,-27.552448,-2.636535,-7.000000,5.088496,14.439655,-0.182482,-23.357664,...,54.929577,-98.858308,19.652404,1137.078688,-4.534606,4.812899,-14.498340,-29.555071,0.0,50.996984
SNSE,11.111113,-2.857145,-41.269842,-14.835170,10.924372,-7.480920,-0.333333,-3.651112,10.408158,-10.746807,...,-15.480229,-19.079906,20.382165,-6.428572,-2.206732,26.872774,-1.503374,232.969438,0.0,49.868294
AFJK,0.686954,0.000000,0.437957,0.290704,0.386473,0.384615,0.287079,0.857961,0.283551,0.943391,...,1.345297,0.000000,0.176987,0.881829,-5.785565,601.864067,-30.661748,-39.888370,0.0,49.744235
BATL,-3.412974,-14.357257,16.599998,-42.905983,-3.031158,1.744184,122.333336,0.000000,-48.125937,-47.878786,...,3.199997,-7.086617,3.418810,0.869564,-1.769910,-0.877192,220.168047,86.486483,0.0,49.364819
GITS,-25.380710,84.782610,-30.873783,-37.113403,14.957264,-10.769230,7.894740,-23.018865,14.018692,-7.142860,...,70.000011,-8.016870,6.363630,-27.736916,-22.413792,-43.360000,408.771930,-40.100248,0.0,47.559638
RXT,-19.387754,11.688316,13.294799,41.904769,-20.136524,4.545450,10.859729,0.210079,15.021466,-16.603775,...,-5.468745,6.779665,-0.704225,15.107917,-32.484082,-4.803918,-37.166324,248.837208,0.0,43.216220

In [156]:
change_t = change_df.transpose()
change_t["FinalScore"] = final_scores
change_t.sort_values("FinalScore", ascending=False).head(15)

Date,2025-02,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,FinalScore
Ticker,,,,,,,,
SBET,2.777775,-32.558137,-18.181819,2104.022889,-82.066100,101.176457,3.967330,262.065955
ABVX,-0.130042,-14.733969,20.882853,-12.879883,20.472444,836.945145,12.627700,187.390194
RGC,-5.349697,686.967771,106.967797,1038.960947,-13.431990,-9.589045,8.326907,181.129090
ASST,-3.623185,15.169655,13.076929,1088.135548,-46.581194,-10.962573,103.642379,154.460000
ZEPP,-2.197800,10.447760,-15.584417,-6.111110,12.711873,377.304977,246.153846,153.159881
DFDV,0.260499,19.019302,1389.799396,48.966943,8.777278,-31.556402,14.021354,132.787533
NAKA,-10.638300,-5.294119,18.238991,1102.127683,-34.969471,-46.950772,-14.330706,114.933589
VOR,-2.702704,-24.579837,9.516132,-69.742815,592.307750,44.755248,-6.190473,94.580859
NEGG,0.000000,-29.729733,-28.846150,34.444452,203.551403,306.305743,-21.670089,92.585130
SUPX,-0.973235,125.944589,6.878313,11.867707,-15.846536,115.980403,153.389213,77.424381
OPEN,-6.293701,-15.702484,-24.577112,-12.834226,-10.720270,225.663724,111.904762,74.172076
PROK,-1.992030,-20.000003,6.746987,-15.339577,-20.643430,390.265485,-16.312058,73.667960
ONDS,1.443299,25.586861,-29.363637,54.626118,30.612239,8.163257,166.363637,60.526508
ABTC,-3.125005,-37.269372,48.427663,351.127805,-17.663546,19.866814,46.666663,59.342666
CELC,-0.736839,13.595507,19.913890,-1.574075,14.888128,213.570870,28.363818,59.331988